import Head from 'next/head';
import { Inter } from '@next/font/google';
import { QueryClient, dehydrate } from 'react-query';
import { getPokemonChunk } from './api/pokemon';
import PageHeader from '@/components/organisms/PageHeader';
import PokemonList from '@/components/organisms/PokemonList';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PageHeader title="Bannano Frontend Challenge" />
                <PokemonList />
            </main>
        </>
    );
}

export async function getServerSideProps() {
    const queryClient = new QueryClient();
    await queryClient.prefetchInfiniteQuery({
        queryKey: ['pokemon'],
        queryFn: async () => getPokemonChunk(),
        initialData: {
            pages: [[]],
            pageParams: [0],
        },
    });

    return { props: { dehydratedState: dehydrate(queryClient) } };
}
